### ISSUE TITLE
Too old resource version

### ISSUE THREAD

**Issue by terrych0u** [DaspawnW/vault-crd#36]
Hi :

I'm using vault-crd 1.4.1 version on aws eks cluster right now, when I was used aws eks 1.14.9  with vault-crd 1.4.1 everything works perfectly.  but when I upgrade my aws eks to 1.15.10,  vault-crd 1.4.1 start crashing and show the following message :

```
| 2020-03-11T04:42:26.010628826Z 2020-03-11 04:42:26.007 ERROR 1 --- [/172.20.0.1/...] d.koudingspawn.vault.kubernetes.Watcher  : Watch for custom │
│  resource failed                                                                                                                                 │
│ 2020-03-11T04:42:26.010653996Z                                                                                                                   │
│ 2020-03-11T04:42:26.010659185Z io.fabric8.kubernetes.client.KubernetesClientException: too old resource version: 47851836 (71336772)             │
│ 2020-03-11T04:42:26.010663896Z     at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$1.onMessage(WatchConnectionManager.java:2 │
│ 63) [kubernetes-client-4.6.4.jar!/:na]                                                                                                           │
│ 2020-03-11T04:42:26.010668776Z     at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:322) [okhttp-3.14.6.jar!/:na]           │
│ 2020-03-11T04:42:26.010674226Z     at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:219) [okhttp-3.14.6.jar!/:na]    │
│ 2020-03-11T04:42:26.010678096Z     at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105) [okhttp-3.14.6.jar!/:na]    │
│ 2020-03-11T04:42:26.010682966Z     at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273) [okhttp-3.14.6.jar!/:na]              │
│ 2020-03-11T04:42:26.010686886Z     at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209) [okhttp-3.14.6.jar!/:na]            │
│ 2020-03-11T04:42:26.010691186Z     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) [okhttp-3.14.6.jar!/:na]                             │
│ 2020-03-11T04:42:26.010695836Z     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.14.6.jar!/:na]                         │
│ 2020-03-11T04:42:26.010708666Z     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212]             │
│ 2020-03-11T04:42:26.010712877Z     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212]             │
│ 2020-03-11T04:42:26.010716496Z     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]                                                       │
│ 2020-03-11T04:42:26.010720107Z                                                                                                                   │
│ 2020-03-11T04:42:36.319008222Z 2020-03-11 04:42:36.318  INFO 1 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down Ex │
│ ecutorService 'vaultThreadPoolTaskScheduler'
```

but if I downgrade vault-crd to 1.3.2 with aws eks 1.15.10, and it wouldn't crash, but it doesn't do anything.

can you help to take a look? it looks like #28 

Thank you

**Comment by DaspawnW** [comment]
Thnx for the info, it seems like the bug was fixed few days ago by fabric8 and released.
I've updated to the latest fabric8 client library.

**Comment by DaspawnW** [comment]
Its now available in release 1.4.2

**Comment by terrych0u** [comment]
Hi 

After I upgrade to vault-crd to 1.4.2, I still face same issue and keep crash,
but if I try to build with fabric8 4.6.2 version, the vault-crd wouldn't crash, and function are working fine.
just the log shows vault-crd keep reconnect every 2 min.
